services:
  - type: web
    name: career-compass-backend
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt && python -m spacy download en_core_web_sm"
    startCommand: "python CareerCompass/backend/app.py"
    envVars:
      - key: PORT
        value: 5000