services:
  - type: web
    name: career-compass-backend
    env: python
    plan: free
    buildCommand: "sh -c \"pip install -r requirements.txt && python -m spacy download en_core_web_sm && python -c 'import spacy; spacy.load(\"'\"'en_core_web_sm'\"'\")'\""
    startCommand: "python CareerCompass/backend/app.py"
    envVars:
      - key: PORT
        value: 5000